# Generated by Django 4.0.3 on 2022-04-30 08:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('status', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('status', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.FloatField(max_length=100)),
                ('vat', models.FloatField(max_length=100)),
                ('total_amount', models.FloatField(max_length=100)),
                ('discount', models.FloatField(max_length=100)),
                ('grand_total', models.FloatField(max_length=100)),
                ('paid', models.FloatField(max_length=100)),
                ('due', models.FloatField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('payment_status', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('status', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('price', models.FloatField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('taxs', models.FloatField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField(max_length=100)),
                ('total', models.FloatField(max_length=100)),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
