# Generated by Django 4.0.3 on 2022-05-11 15:08

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('status', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creación')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.FloatField(max_length=100)),
                ('vat', models.FloatField(max_length=100)),
                ('total_amount', models.FloatField(max_length=100)),
                ('discount', models.FloatField(max_length=100)),
                ('grand_total', models.FloatField(max_length=100)),
                ('paid', models.FloatField(max_length=100)),
                ('due', models.FloatField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('payment_status', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('status', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creación')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('price', models.FloatField(max_length=100, verbose_name='precio')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='código')),
                ('quantity', models.IntegerField(default=0, verbose_name='cantidad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('taxs', models.FloatField(blank=True, default=0, max_length=100, null=True, verbose_name='IVA')),
                ('status', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creación')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand', verbose_name='marca')),
                ('tag', models.ManyToManyField(to='products.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField(max_length=100)),
                ('total', models.FloatField(max_length=100)),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
