# Generated by Django 4.0.3 on 2022-05-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_name_alter_product_name_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delete_date',
            field=models.DateField(auto_now=True, verbose_name='Feacha de eliminacion'),
        ),
        migrations.AddField(
            model_name='product',
            name='upgrated_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AddField(
            model_name='tag',
            name='delete_date',
            field=models.DateField(auto_now=True, verbose_name='Feacha de eliminacion'),
        ),
        migrations.AddField(
            model_name='tag',
            name='upgrated_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
    ]
