# Generated by Django 4.0.3 on 2022-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taxs',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='IVA'),
        ),
    ]
