# Generated by Django 4.0.3 on 2022-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_delete_date_product_upgrated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='products.tag', verbose_name='Tag'),
        ),
    ]
