# Generated by Django 4.0.3 on 2022-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taxs',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True, verbose_name='IVA'),
        ),
    ]
