# Generated by Django 4.0.3 on 2022-07-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_tag_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
